### ISSUE TITLE
[bug] Error: Could not resolve '../models/Serie' from src/service/Serie.js

### ISSUE THREAD

**Issue by raulfdm** [raulfdm/sub-tv#21]
After #17, the build fails:

```
$ yarn build
yarn run v1.12.3
$ rollup -c

src/index.js → dist/subtv.js...
[!] Error: Could not resolve '../models/Serie' from src/service/Serie.js
Error: Could not resolve '../models/Serie' from src/service/Serie.js
    at error (/Users/raulmelo/projects/personal/sub-tv/node_modules/rollup/dist/rollup.js:3597:30)
    at /Users/raulmelo/projects/personal/sub-tv/node_modules/rollup/dist/rollup.js:17532:25

error Command failed with exit code 1.
```

**Comment by raulfdm** [comment]
invalid by #31
