### ISSUE TITLE
Cannot read property name from undefined

### ISSUE THREAD

**Issue by raulfdm** [raulfdm/sub-tv#3]
# Scenario
- **Serie**: Mr Robot
- **Season**: Season 1
- **Episode**:  Episode 8
- **Language**: English
- **Subtitle**: Rating: -2 | Name: Mr.Robot.S01E08.REAL.720p.HDTV.x264-KIL
LERS

## Error Trace
```javascript
Trace: TypeError: Cannot read property 'name' of undefined
    at Promise (/home/raul/.npm-global/lib/node_modules/sub-tv/src/service/Download.js:11:21)
    at Promise (<anonymous>)
    at download (/home/raul/.npm-global/lib/node_modules/sub-tv/src/service/Download.js:7:10)
    at bootstrap (/home/raul/.npm-global/lib/node_modules/sub-tv/src/index.js:83:26)
    at <anonymous>
    at bootstrap (/home/raul/.npm-global/lib/node_modules/sub-tv/src/index.js:87:13)
    at <anonymous>
```

**Comment by raulfdm** [comment]
Couldn't reproduce. maybe fixed by #31
